[2024-05-03T15:37:46.106+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: accident_api_pipeline.get_accident_api manual__2024-04-21T14:13:04.827961+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
